import { describe, it, expect } from 'vitest';
import { urlParse } from '@/lib/utils/path';

describe('Path Util functions', () => {
  describe('urlParse', () => {
    it('is a function', () => {
      expect(urlParse).toBeTypeOf('function');
    });

    describe('should parse a url', () => {
      const testUrlList = [
        'https://example.com:300/example/minge/file.min.test#min?win=onw',
        'https://example.com:300/example/minge/file.min.test#min?win&tie=1',
        'https://example.com:300/example/minge/file.min.test?win&tie=1',
        'https://example.com:300/example/minge/file.min.test#min',
        'https://example.com:300/example/minge/file.min.test',
        'https://example.com:300/example/minge/file.mintest#min',
        'https://example.com:300/example/minge/filemintest#min',
        'https://example.com:300/example/minge/filemintest?win',
        'https://example.com:300/example/minge/filemintest',
        'https://example.com:300/example/minge/filemintest#min?win&tie=1',
        'https://example.com:300/example/minge/#min?win&tie=1',
        'https://example.com/example/minge/#min?win&tie=1',
        'https://example.com/#min?win&tie=1',
        'https://example.com/?win&tie=1',
        'https://example.com/#min',
        'https://example.com/',
        'https://example.com#min?win&tie=1',
        'https://example.com?win&tie=1',
        'https://example.com#min',
        'https://example.com',
        'https://example.com:3000#min?win&tie=1',
        'https://example.com:3000?win&tie=1',
        'https://example.com:3000#min',
        'https://example.com:3000',
        'https://127.0.0.1:3000#min?win&tie=1',
        'https://127.0.0.1:3000?win&tie=1',
        'https://127.0.0.1:3000#min',
        'https://127.0.0.1:3000',
        'https://127.0.0.1#min?win&tie=1',
        'https://127.0.0.1?win&tie=1',
        'https://127.0.0.1#min',
        'https://127.0.0.1',
        'file:///url/minev.test.ts',
        'file:///url/minev test.ts',
        'file:///url/minev test',
        'file:///url/minevtest',
        'file:///url/',
      ];
      const expectedResultList = [
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file.min',
          extension: 'test',
          selector: 'min',
          query: {
            win: 'onw',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file.min',
          extension: 'test',
          selector: 'min',
          query: {
            tie: '1',
            win: '',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file.min',
          extension: 'test',
          selector: null,
          query: {
            tie: '1',
            win: '',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file.min',
          extension: 'test',
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file.min',
          extension: 'test',
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'file',
          extension: 'mintest',
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'filemintest',
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'filemintest',
          extension: null,
          selector: null,
          query: {
            win: '',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'filemintest',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: 'filemintest',
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 300,
          root: '/',
          path: 'example/minge/',
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: '/',
          path: 'example/minge/',
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: '/',
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: '/',
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: '/',
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: '/',
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: 'example.com',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: 3000,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: {
            win: '',
            tie: '1',
          },
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: 'min',
          query: null,
        },
        {
          protocol: 'https',
          hostname: '127.0.0.1',
          port: null,
          root: null,
          path: null,
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'file',
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev.test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: 'file',
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: 'file',
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev test',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'file',
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minevtest',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: 'file',
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
      ];
      testUrlList.forEach((testUrl, index) => {
        it(`should parse "${testUrl}" correctly`, () => {
          const expectedResult = expectedResultList[index];
          const result = urlParse(testUrl);
          expect(result).toEqual(expectedResult);
        });
      });
    });

    describe('should parse a file path', () => {
      const testUrlList = [
        '/url/minev.test.ts',
        '/url/minev test.ts',
        '/url/minev test',
        '/url/minevtest',
        '/url/',
        'url/minev.test.ts',
        'url/minev test.ts',
        'url/minev test',
        'url/minevtest',
        'url/',
        'minte.ts',
        'mintets',
      ];
      const expectedResultList = [
        {
          protocol: null,
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev.test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minev test',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: 'minevtest',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: '/',
          path: 'url/',
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: 'url/',
          file: 'minev.test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: 'url/',
          file: 'minev test',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: 'url/',
          file: 'minev test',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: 'url/',
          file: 'minevtest',
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: 'url/',
          file: null,
          extension: null,
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: null,
          file: 'minte',
          extension: 'ts',
          selector: null,
          query: null,
        },
        {
          protocol: null,
          hostname: null,
          port: null,
          root: null,
          path: null,
          file: 'mintets',
          extension: null,
          selector: null,
          query: null,
        },
      ];
      testUrlList.forEach((testUrl, index) => {
        it(`should parse "${testUrl}" correctly`, () => {
          const expectedResult = expectedResultList[index];
          const result = urlParse(testUrl);
          expect(result).toEqual(expectedResult);
        });
      });
    });
  });
});
